services:
  backend:
    image: veetik/bm_backend:${COMMIT_SHA:-latest}
    networks:
      - proxy
      - pg
    logging:
      options:
        max-size: 2m
        max-file: 3
    secrets:
      - source: bm_envs
        target: /.env
    deploy:
      rollback_config:
        parallelism: 2
        delay: 5s
        failure_action: continue
        monitor: 5s
        order: start-first
      update_config:
        parallelism: 2
        delay: 1s
        failure_action: rollback
        monitor: 5s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.bm_backend.rule=Host(`bm_back.veetik.com`)"
        - "traefik.http.services.bm_backend.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  pg:
    external: true

secrets:
  bm_envs:
    external: true

